# Generated by Django 5.0.2 on 2024-03-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
