# Generated by Django 5.0.2 on 2024-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descimage1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='descimage2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='descimage3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
