# Generated by Django 5.0.2 on 2024-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_item_descimage1_item_descimage2_item_descimage3'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
