# Generated by Django 5.0.2 on 2024-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
