# Generated by Django 5.0.2 on 2024-03-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_order_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
    ]
