# Generated by Django 5.0.2 on 2024-03-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
