# Generated by Django 5.0.2 on 2024-03-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_rename_country_customerdetail_country_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='country_code',
        ),
    ]
