# Generated by Django 5.0.2 on 2024-04-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_rename_country_name_customerdetail_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('featured', 'Featured'), ('latest', 'Latest')], max_length=10, null=True),
        ),
    ]
