# Generated by Django 5.0.2 on 2024-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_item_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('size-A', 'Size A'), ('size-B', 'Size B'), ('size-C', 'Size C'), ('size-D', 'Size D')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size_category',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=10, null=True),
        ),
    ]
