# Generated by Django 5.0.2 on 2024-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_item_size_item_size_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('Size A', 'Size A'), ('Size B', 'Size B'), ('Size C', 'Size C'), ('Size D', 'Size D')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size_category',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=10, null=True),
        ),
    ]
