# Generated by Django 5.0.2 on 2024-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_remove_item_size_remove_item_size_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('clothing&footwear', 'Clothing & Footwear'), ('electronics', 'Electronics')], max_length=20, null=True),
        ),
    ]
