# Generated by Django 5.0.2 on 2024-06-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_checkoutdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.checkoutdetails'),
        ),
    ]
