# Generated by Django 5.0.2 on 2024-06-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_order_checkout_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutDetails',
            new_name='CheckoutDetail',
        ),
    ]
